MNT: Error if requirements files not found

diff --git a/travis/shared_configs/doctr-upload.yml b/travis/shared_configs/doctr-upload.yml
--- a/travis/shared_configs/doctr-upload.yml
+++ b/travis/shared_configs/doctr-upload.yml
@@ -7,8 +7,11 @@ jobs:
         - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
         - |
           # Install docs requirements
-          if [[ -f "${DOCS_REQUIREMENTS}" ]]; then
-            pip install --upgrade --requirement "${DOCS_REQUIREMENTS}"
+          if [[ ! -f "${DOCS_REQUIREMENTS}" ]]; then
+              echo "File not found: ${DOCS_REQUIREMENTS}" 1>&2
+              travis_terminate 1
+          else
+              pip install --upgrade --requirement "${DOCS_REQUIREMENTS}"
           fi
       before_script:
         - |
diff --git a/travis/shared_configs/python_tester.yml b/travis/shared_configs/python_tester.yml
--- a/travis/shared_configs/python_tester.yml
+++ b/travis/shared_configs/python_tester.yml
@@ -6,8 +6,22 @@ python:
 install:
   - echo "Req File':' ${REQUIREMENTS:=requirements.txt}"
   - echo "Dev Req File':' ${DEV_REQUIREMENTS:=dev-requirements.txt}"
-  - pip install --upgrade --requirement requirements.txt
-  - pip install --upgrade --requirement dev-requirements.txt
+  - |
+    # Install requirements
+    if [[ ! -f "${REQUIREMENTS}" ]]; then
+        echo "File not found: ${REQUIREMENTS}" 1>&2
+        travis_terminate 1
+    else
+        pip install --upgrade --requirement "${REQUIREMENTS}"
+    fi
+  - |
+    # Install development requirements
+    if [[ ! -f "${DEV_REQUIREMENTS}" ]]; then
+        echo "File not found: ${DEV_REQUIREMENTS}" 1>&2
+        travis_terminate 1
+    else
+        pip install --upgrade --requirement "${DEV_REQUIREMENTS}"
+    fi
 
 script:
   - coverage run run_tests.py
